### ISSUE TITLE
Invisible icons

### ISSUE THREAD

**Issue by Toucani** [daledavies/jump#59]
Hi!

While using Jump for the last several months I've noticed a random bug when the icons of the websites become invisible. They are present, because when I hoover the mouse over - I can see the tooltip, and clicking them also works. When this happened last time I've noticed some errors in the logs so I thought it would be at least a starting point:)

## Screenshots

First, screenshots made with Safari and Firefox(notice the tooltip and the address in the lower left corner):

1. ![Screenshot 2022-08-11 at 16 04 32](https://user-images.githubusercontent.com/97796217/184396349-b3416734-7e66-48a9-a680-9f9ff7eea804.jpg)
1. ![Screenshot 2022-08-11 at 16 04 38](https://user-images.githubusercontent.com/97796217/184396385-8fdfc5ec-7e60-4f48-bda6-3af8972bf52f.jpg)
1. ![Screenshot 2022-08-11 at 16 04 46](https://user-images.githubusercontent.com/97796217/184396395-9093c073-d92d-4ec0-b6cb-ac267f9f4a61.jpg)
1. ![Screenshot 2022-08-11 at 16 04 54](https://user-images.githubusercontent.com/97796217/184396407-cc64c2f2-be3f-4774-a4b8-d32720774c64.jpg)

## Details

I was able to reproduce it on 1.3.0 and 1.2.4. Can test on any older version if needed.

Unfortunately, I haven't found the exact steps to make it happen. However, when it happened I tried doing this:
- restart the container
- stop container, remove image, download image, start container
- flip `CACHE_BYPASS` variable
- drop `favicon` and `search` features

none of these actions helped.

### Docker command
Here is the command that I used
```
docker run -d --restart unless-stopped \
-v "<path>/Containers/jump/sites:/sites" \
-v "<path>/Containers/jump/favicon:/favicon" \
-v "<path>/Containers/jump/search:/search" \
-v "<path>/Containers/jump/backgrounds:/backgrounds" \
-e SITENAME="Name" \
-e SHOWCLOCK="true" \
-e AMPMCLOCK="false" \
-e SHOWGREETING="true" \
-e SHOWSEARCH="true" \
-e ALTLAYOUT="false" \
-e CHECKSTATUS="false" \
-e BGBLUR="60" \
-e BGBRIGHT="50" \
-e NOINDEX="true" \
-e OWMAPIKEY="<some gibberish>" \
-e METRICTEMP="true" \
-e LATLONG="LAT, LON" \
-l traefik.enable=true \
... some traefik labels ...
--name jump daledavies/jump:v1.3.0
```

### Steps to reproduce
1. Run the command
1. ???
1. Profit!!!

### Errors that I saw
```
Aug 12 13:17:05 Homeserver 008dbb353f56[48783]: 2022/08/12 12:17:05 [error] 25#25: *23 open() "/var/www/html/images/tags.svg" failed (2: No such file or directory), client: 172.17.0.5, server: _, request: "GET /images/tags.svg HTTP/1.1", host: "aviary.lan", referrer: "http://aviary.lan/"
Aug 12 13:17:05 Homeserver 008dbb353f56[48783]: 2022/08/12 12:17:05 [error] 26#26: *26 open() "/var/www/html/images/search.svg" failed (2: No such file or directory), client: 172.17.0.5, server: _, request: "GET /images/search.svg HTTP/1.1", host: "aviary.lan", referrer: "http://aviary.lan/"
Aug 12 13:17:05 Homeserver 008dbb353f56[48783]: 2022/08/12 12:17:05 [error] 25#25: *25 open() "/var/www/html/images/loading.svg" failed (2: No such file or directory), client: 172.17.0.5, server: _, request: "GET /images/loading.svg HTTP/1.1", host: "aviary.lan", referrer: "http://aviary.lan/"
```

So naturally, I logged into the container and did this

```
bash-5.1# ls /var/www/html/images
ls: /var/www/html/images: No such file or directory

bash-5.1# find / -name "tags.svg"
/var/www/html/assets/images/tags.svg
/usr/src/jumpapp/assets/images/tags.svg

```

Looks like a path has been changed but not updated somewhere in the code?

I can also provide a full log where I saw the errors if this is of any interest:) Let me know if I can help with it any further:)

**Comment by Toucani** [comment]
Looking at the errors, I think this might come from some inconsistency with the relative paths used in 
- https://github.com/daledavies/jump/blob/c9bbc908609ef22fb58d60dec7fa4b96b2e7a442/jumpapp/assets/css/src/_header-bar.scss#L16
- https://github.com/daledavies/jump/blob/0cf55c9917188820a159927555ea4ee48e00d289/jumpapp/assets/css/src/_sites.scss#L47
- https://github.com/daledavies/jump/blob/c9bbc908609ef22fb58d60dec7fa4b96b2e7a442/jumpapp/assets/css/src/_search.scss#L9

So it either should be `.../assets/images/image.svg` or `/images/image.svg` if we're in the assets folder alread...

**Comment by daledavies** [comment]
Howdy, thanks for reaching out!

It is odd why you're seeing errors for just those three assets. Especially as your screenshots show those icons have loaded.

 You should look in this file for the image URLs that are used as this is the CSS bundle created by webpack... 

https://github.com/daledavies/jump/blob/main/jumpapp/assets/css/styles.00c4db10d75e0c01f6eb.min.css

The issue shown in your screenshots however seems like jump isn't getting the response it expects from the Open Weather Map API. Could you post any errors you see in your browser's javascript console?

**Comment by daledavies** [comment]
I've actually identified a fix for the issue I think might be happening, so even if jump gets an error from open weather it will still finish loading, this will be included in the next release. 

But I'm curious as to whether this is the problem you're facing and seeing if there are any errors in the javascript console will help identify that 😀

**Comment by Toucani** [comment]
Huh... Interesting. The console indeed shows an error related to OpenWeather:
```
[Error] JUMP ERROR: There was an issue with the OWM API... Could not resolve host: api.openweathermap.org
	(anonymous function) (index.67685b39ff36ec927e35.min.js:1:22969)
	promiseReactionJob
```

I've just `ping api.openweathermap.org` it and it resolves ok from the machine. After this the error is gone from the console, but the icons are still invisible.

I've also checked the css file, and it seems that the links are `background-image: url(../images/tags.svg);`:
```
.time-weather
{
	bottom: 10px;
	display: block;
	font-family: Quicksand,sans-serif;
	font-weight: 400;
	position: absolute;
	right: 15px;
	text-shadow: 1px 1px 2px rgba(0,0,0,.627);
	z-index: 1000
}

.time-weather .time
{
	font-size: 2.4em;
	vertical-align: middle
}

.time-weather .time span
{
	font-size: .5em;
	padding-left: 5px
}

.time-weather .weather
{
	color: inherit;
	text-decoration: none
}

.time-weather .weather .weather-icon
{
	display: inline-block;
	font-size: 1.9em;
	height: 48px;
	line-height: 48px!important;
	vertical-align: middle
}

.time-weather .weather .weather-icon:before
{
	position: relative
}

.time-weather .weather .weather-info
{
	display: inline-flex;
	flex-direction: column;
	font-size: 14px;
	font-weight: 600;
	line-height: normal;
	margin-right: 10px;
	text-align: right;
	text-shadow: 1px 1px 1px rgba(0,0,0,.627);
	vertical-align: middle
}

.widget
{
	display: inline-block;
	height: 58px;
	padding: 5px 10px;
	user-select: none;
	z-index: 1000
}

.widget.clickable
{
	border-radius: 6px;
	cursor: pointer
}

.widget.clickable:hover
{
	background-color: hsla(0,0%,100%,.082);
	transition: background-color .1s
}

.useclientlocation
{
	background-image: url(../images/map-pin.svg);
	background-position: top 50% left 5px;
	background-repeat: no-repeat;
	background-size: 37px;
	bottom: 10px;
	display: none;
	font-size: 14px;
	left: 15px;
	line-height: 58px;
	padding: 0 10px 0 45px;
	position: absolute;
	text-shadow: 1px 1px 1px rgba(0,0,0,.627)
}

.greeting
{
	font-family: Quicksand,sans-serif;
	font-size: 2.3em;
	font-weight: 400;
	margin-bottom: 15px;
	text-shadow: 1px 1px 2px rgba(0,0,0,.627);
	text-transform: capitalize
}

.greeting .tagname
{
	text-transform: lowercase
}

.greeting .tagname .greeting .tagname span
{
	margin-right: 5px;
	opacity: .5
}

.header-bar
{
	left: 0;
	padding: 15px 15px 0;
	position: absolute;
	right: 0;
	text-align: right;
	top: 0;
	z-index: 100
}

.header-bar .show-tags
{
	background-color: hsla(0,0%,100%,.082);
	background-image: url(../images/tags.svg);
	background-position: top 50% left 50%;
	background-repeat: no-repeat;
	background-size: 35px;
	border: 2px solid hsla(0,0%,100%,.125);
	border-radius: 50%;
	cursor: pointer;
	display: inline-block;
	height: 55px;
	width: 55px
}

.header-bar .show-tags:hover
{
	background-color: #fff;
	background-image: url(../images/tags-dark.svg);
	border: 2px solid #cecece;
	box-shadow: 0 1px 5px rgba(0,0,0,.3);
	transition: background-color,background-image .1s
}

.search
{
	background-color: hsla(0,0%,100%,.082);
	background-image: url(../images/search.svg);
	background-position: top 13px left 13px;
	background-repeat: no-repeat;
	background-size: 24px;
	border: 2px solid hsla(0,0%,100%,.125);
	border-radius: 50%;
	cursor: pointer;
	display: block;
	font-family: Quicksand,sans-serif;
	height: 55px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	top: 15px;
	width: 55px
}

.search.open,.search:hover
{
	background-color: #fff;
	background-image: url(../images/search-dark.svg);
	border: 2px solid #cecece;
	box-shadow: 0 1px 5px rgba(0,0,0,.3);
	transition: background-color,background-image .1s
}

.search.open
{
	border: .2em solid #cecece;
	border-radius: 5px;
	box-shadow: 0 1px 5px rgba(0,0,0,.3);
	cursor: auto;
	max-width: 450px;
	width: calc(100% - 30px)
}

.search.open .close
{
	background-image: url(../images/close-dark.svg);
	background-position: top 50% left 50%;
	background-repeat: no-repeat;
	background-size: 30px;
	border: 5px solid #fff;
	border-radius: 50%;
	cursor: pointer;
	display: inline-block;
	height: 48px;
	position: absolute;
	right: 0;
	top: 0;
	width: 48px;
	z-index: 1
}

.search.open .close.search.open,.search.open .close:hover
{
	background-color: #f3f3f3
}

.search.open .search-form
{
	display: inline-block
}

.search.suggestions
{
	height: auto
}

.search.suggestions .suggestion-list
{
	border-top: 1px solid #ddd;
	color: #202124;
	display: block;
	font-size: 15px;
	margin-top: 25px;
	padding-bottom: 10px;
	padding-top: 20px;
	text-align: left
}

.search.suggestions .suggestion-list .selected
{
	border: 1px solid red
}

.search.suggestions .suggestion-list ul
{
	list-style-type: none;
	margin: 0;
	padding: 10px 0 0
}

.search.suggestions .suggestion-list ul li a
{
	color: inherit;
	display: block;
	padding: 5px 0 5px 15px;
	text-decoration: none
}

.search.suggestions .suggestion-list ul li a.search.open,.search.suggestions .suggestion-list ul li a:focus,.search.suggestions .suggestion-list ul li a:hover
{
	background-color: #eee;
	outline: none
}

.search.suggestions .suggestion-list .searchproviders
{
	margin-bottom: 20px
}

.search.suggestions .suggestion-list .searchproviders li a
{
	background-image: url(../images/search-dark.svg);
	background-position: top 50% left 15px;
	background-repeat: no-repeat;
	background-size: 17px;
	display: block;
	padding-left: 50px
}

.search.suggestions .suggestion-list .searchproviders li a span
{
	color: #999
}

.search.suggestions .suggestion-list .suggestiontitle
{
	color: #888;
	display: block;
	font-size: 15px;
	margin: 0 0 0 15px;
	text-transform: uppercase
}

.search.suggestions .suggestion-list ul.suggestions
{
	padding-bottom: 15px
}

.search.suggestions .suggestion-list .icon
{
	margin-right: 15px;
	vertical-align: middle;
	width: 20px
}

.search.suggestions .suggestion-list .name
{
	vertical-align: middle
}

.search .search-form
{
	color: #202124;
	display: none;
	overflow: hidden;
	padding-right: 48px;
	position: relative;
	text-align: left;
	top: 14px;
	width: calc(100% - 35px)
}

.search .search-form input
{
	background: transparent;
	border: none;
	color: #202124;
	display: block;
	font-family: Quicksand,sans-serif;
	font-size: 17px;
	margin: 0;
	outline: none;
	padding: 0 0 0 15px;
	position: relative;
	width: 100%
}

.search .search-form input[type=search]::-ms-clear,.search .search-form input[type=search]::-ms-reveal
{
	display: none;
	height: 0;
	width: 0
}

.search .search-form input[type=search]::-webkit-search-cancel-button,.search .search-form input[type=search]::-webkit-search-decoration,.search .search-form input[type=search]::-webkit-search-results-button,.search .search-form input[type=search]::-webkit-search-results-decoration
{
	display: none
}

.sites,.sites li
{
	font-size: 14px;
	list-style-type: none;
	margin: 0;
	padding: 0;
	user-select: none
}

.sites li,.sites li a
{
	display: inline-block
}

.sites li a
{
	border-radius: 6px;
	color: inherit;
	padding: 12px;
	text-decoration: none
}

.sites li a:hover
{
	background-color: hsla(0,0%,100%,.082);
	transition: background-color .1s
}

.sites .icon
{
	background-color: #fff;
	background-image: url(../images/loading.svg);
	background-position: 50%;
	background-repeat: no-repeat;
	background-size: 20px;
	border: .2em solid #fff;
	border-radius: 6px;
	box-shadow: 0 1px 5px rgba(0,0,0,.3);
	display: block;
	height: 80px;
	margin-bottom: 8px;
	padding: 15px;
	position: relative;
	width: 80px
}

.sites .icon img
{
	background: #fff;
	width: 100%
}

.sites .name
{
	word-wrap: break-word;
	display: block;
	max-height: 3.3em;
	overflow: hidden;
	text-overflow: ellipsis;
	text-shadow: 1px 1px 1px rgba(0,0,0,.627);
	white-space: nowrap;
	width: 80px
}

.status .sites:not(.alternate) .icon
{
	border: none;
	height: 82px;
	overflow: hidden
}

.status .sites:not(.alternate) .icon:after
{
	background-color: #ccc;
	bottom: 0;
	content: "";
	display: inline-block;
	height: 4px;
	left: 0;
	position: absolute;
	width: 100%
}

.status .sites:not(.alternate) .online .icon:after
{
	background-color: #55e22a
}

.status .sites:not(.alternate) .offline .icon:after
{
	background-color: #ec2c2c
}

.status .sites:not(.alternate) .error .icon:after
{
	background-color: #ddd900
}

.status .sites.alternate li a
{
	padding-left: 11px;
	position: relative
}

.status .sites.alternate li a:before
{
	background-color: #ccc;
	content: "";
	display: inline-block;
	height: 100%;
	left: 0;
	position: absolute;
	top: 0;
	width: 4px
}

.status .sites.alternate li.online a:before
{
	background-color: #55e22a
}

.status .sites.alternate li.offline a:before
{
	background-color: #ec2c2c
}

.status .sites.alternate li.error a:before
{
	background-color: #ddd900
}

.sites.alternate
{
	margin-top: 20px;
	width: 100%
}

.sites.alternate li
{
	float: left;
	margin-bottom: 10px;
	padding: 0 5px;
	text-align: left;
	width: 50%
}

.sites.alternate li a
{
	background-color: hsla(0,0%,100%,.8);
	box-shadow: 0 1px 5px rgba(0,0,0,.3);
	overflow: hidden;
	padding: 8px;
	position: relative;
	transition: background-color .1s,box-shadow .1s;
	width: 100%
}

.sites.alternate li a:hover
{
	background-color: #fff;
	box-shadow: 0 1px 5px rgba(0,0,0,.6)
}

.sites.alternate .icon
{
	border: none;
	border-radius: 6px;
	box-shadow: none;
	display: inline-block;
	height: 35px;
	margin: 0 8px 0 0;
	overflow: hidden;
	padding: 0;
	vertical-align: middle;
	width: 35px
}

.sites.alternate .name
{
	color: #202124;
	display: inline-block;
	height: 14px;
	line-height: 14px;
	margin-top: -7px;
	position: absolute;
	text-shadow: none;
	top: 50%;
	vertical-align: middle;
	width: auto
}

@media(max-width:500px)
{
	.sites.alternate li
	{
		width: 100%
	}
}

.tags
{
	background-color: #fff;
	border: .2em solid #cecece;
	border-radius: 6px;
	box-shadow: 0 1px 5px rgba(0,0,0,.3);
	color: #202124;
	display: none;
	font-family: Quicksand,sans-serif;
	font-weight: 400;
	min-width: 250px;
	padding: 15px;
	position: fixed;
	right: 15px;
	text-align: left;
	top: 15px;
	z-index: 100
}

.tags:target
{
	display: block
}

.tags .header
{
	border-bottom: 1px solid #ddd;
	display: block;
	font-size: 20px;
	height: 35px;
	line-height: 18px;
	margin-bottom: 20px
}

.tags .header .close
{
	background-image: url(../images/close-dark.svg);
	background-position: top 50% left 50%;
	background-repeat: no-repeat;
	background-size: 30px;
	border: 5px solid #fff;
	border-radius: 50%;
	cursor: pointer;
	display: inline-block;
	height: 48px;
	position: absolute;
	right: 0;
	top: 0;
	width: 48px
}

.tags .header .close:hover
{
	background-color: #f3f3f3
}

.tags ul
{
	list-style-position: inside;
	margin: 0;
	padding: 0
}

.tags ul li
{
	margin-bottom: 3px;
	text-transform: lowercase
}

.tags ul li::marker
{
	color: #bbb;
	content: "#"
}

.tags ul li a
{
	border-radius: 4px;
	color: inherit;
	display: inline-block;
	margin-left: 1px;
	padding: 3px 5px;
	text-decoration: dotted
}

.tags ul li a:hover
{
	background-color: #f3f3f3;
	transition: background-color .1s
}

@font-face
{
	font-family:Quicksand;font-style:normal;font-weight:400;src:local(""),url(../font/quicksand-v28-latin-regular.woff2) format("woff2"),url(../font/quicksand-v28-latin-regular.woff) format("woff")
}

*
{
	box-sizing: border-box
}

body
{
	background: #000;
	color: #fff;
	font-family: sans-serif;
	margin: 0;
	padding: 0;
	text-align: center
}

.fixed
{
	bottom: 0;
	left: 0;
	position: fixed;
	right: 0;
	top: 0
}

.hidden
{
	opacity: 0
}

.enable
{
	display: block!important
}

.background
{
	background-position: 50%;
	background-repeat: no-repeat;
	background-size: cover;
	transform: scale(1.07);
	z-index: 1
}

.unsplash
{
	bottom: 23px;
	display: block;
	font-family: Quicksand,sans-serif;
	font-size: 11px;
	opacity: .6;
	position: fixed;
	text-align: center;
	width: 100%;
	z-index: 100
}

.unsplash a
{
	color: inherit;
	text-decoration: none
}

.unsplash a:hover
{
	font-weight: 700
}

@media(max-width:850px)
{
	.unsplash
	{
		display: none
	}
}

.content
{
	display: flex;
	flex-direction: column;
	justify-content: center;
	margin: -50px auto 0;
	max-width: 650px;
	width: 100%;
	z-index: 100
}

```

**Comment by rdos14** [comment]
i had the same issue with the icons not showing, but they are there because when i hover over the area that they are supposed to be.  I can help with any information that you need to track the issue

**Comment by daledavies** [comment]
Can you provide a screenshot of the javascript console from devtools?

**Comment by daledavies** [comment]
Note I do not think there is a CSS issue

**Comment by rdos14** [comment]
@daledavies in my case was the LATLONG variable, i put just like google maps give it to me 20.456600, -97.987094.

Notice the space after the comma, i delete that space and now everything works!

**Comment by daledavies** [comment]
Awesome, glad you got it working. Thanks for reaching out 😀

**Comment by cinderblockgames** [comment]
Following; I've just started using this dashboard and I also get invisible icons sometimes.

**Comment by MyNameIsTito** [comment]
bump, same issue here

**Comment by Toucani** [comment]
For all the interested people here is what was my original problem: the container was not able to resolve hostnames at all due to DNS misconfiguration. This is why [I had a resolution error that went away after `ping`](https://github.com/daledavies/jump/issues/59#issuecomment-1213348951).

It looks like any network issue(eg. resolution problem, API problem, etc) would lead to invisible icons...

**Comment by cinderblockgames** [comment]
@Toucani This makes a lot of sense; I just fixed DNS issues, so that could have been it.

**Comment by MyNameIsTito** [comment]
Ending up resolving it after removing the following lines from the **environment** section of the `docker-compose.yml`

```
            OWMAPIKEY: '0a1b2c3d4e5f6a7b8c9d0a1b'
            LATLONG: '51.509865,-0.118092'
```

**Comment by cinderblockgames** [comment]
@MyNameIsTito That's fine if you don't want weather on the page; otherwise, you should replace those with your own key and position.

**Comment by MyNameIsTito** [comment]
> @MyNameIsTito That's fine if you don't want weather on the page; otherwise, you should replace those with your own key and position.

Yes, that is true @cinderblockgames but what's the fix 🤔 

I've even added my own key and `LATLONG` still have an error of "not being able to see anything"

**Comment by daledavies** [comment]
Hi everyone, thank you for keeping up the discussion on this issue. Just wanted to let you know I have not disappeared but I did need to take a little break.

Although there are some improvements I do want to make that will stop the icons from being invisible if there is an error from the open weather API, debugging what is actually going on with the API call is difficult for me to do if I can't recreate it. 

There should be some error logged in either the devtools console or docker logs that will indicate an API error, can you check to see?

**Comment by JarlMorgennebel** [comment]
Same issue.

Solved by removing the DEFAULT added OWMAPIKEY and LATLONG entries from sites/sites_json, removing the old container and restarting again. Works fine now.

Changed nothing for DNS.

**Comment by cinderblockgames** [comment]
If you're in swarm mode, make sure you either have sticky sessions or only one replica.

**Comment by daledavies** [comment]
I've fixed a few small issues that might help with this. One last thing I'll do is detach the site icon visibility from loading the greeting/weather. That way if the localisation information can't be fetched from the weather API you'll still be able to access sites.

**Comment by daledavies** [comment]
A note for future people who see this thread. You must remove the OWMAPIKET and LATLONG that are mentioned in the Readme examples, they are there for example purposes only and will not actually work.

**Comment by daledavies** [comment]
> @daledavies in my case was the LATLONG variable, i put just like google maps give it to me 20.456600, -97.987094.
> 
> Notice the space after the comma, i delete that space and now everything works!

@rdos14 This will now be fixed by commit https://github.com/daledavies/jump/commit/8810450b8cf26e402a77a133fcb2b4d3f611ff47

**Comment by daledavies** [comment]
A number of small fixes have been applid in the latest release (v1.3.2) so let's see how this goes, closing the issue for now.

Thanks everyone :)

**Comment by daledavies** [comment]
Amazing! Thank you so much for taking the time to let me know :)
